version: 2.1

parameters:
  eventType:
    default: "test"
    type: string
    
  branchName:
    default: "test"
    type: string   

  sourceBranchName:
    default: "test"
    type: string


#----------------------------   - ----------------------------------------------------------
jobs:
  developer-deploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - run:
          name: "DEV PUSH"
          command: npm --version

  qa-deploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - run:
          name: "QA PUSH"
          command: npm --version

  uat-deploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - run:
          name: "UAT PUSH"
          command: npm --version

  prod-deploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - run:
          name: "PROD  PUSH"
          command: npm --version

  developer-predeploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - run:
          name: "DEV PR"
          command: |
            npm --version
            echo << pipeline.parameters.eventType >>
            echo << pipeline.parameters.branchName >>
            echo << pipeline.parameters.sourceBranchName >>

  qa-predeploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - run:
          name: "QA PR"
          command: |
            npm --version
            echo << pipeline.parameters.eventType >>
            echo << pipeline.parameters.branchName >>
            echo << pipeline.parameters.sourceBranchName >>

  uat-predeploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - run:
          name: "UAT PR"
          command: npm --version

  prod-predeploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - run:
          name: "PROD PR"
          command: npm --version


#------------------------------      --------------------------------------------------------


workflows:
  version: 2
  developer-deploy:
    when:
      and:
        - equal: [ "push", << pipeline.parameters.eventType >> ]
        - equal: [ "dev", << pipeline.parameters.branchName >> ]
    jobs:
      - developer-deploy
  
  qa-push-workflow:
    when:
      and:
        - equal: [ "push", << pipeline.parameters.eventType >> ]
        - equal: [ "qa", << pipeline.parameters.branchName >> ]
    jobs:
      - qa-deploy

  uat-push-workflow:
    when:
      and:
        - equal: [ "push", << pipeline.parameters.eventType >> ]
        - equal: [ "uat", << pipeline.parameters.branchName >> ]
    jobs:
      - uat-deploy

  prod-push-workflow:
    when:
      and:
        - equal: [ "push", << pipeline.parameters.eventType >> ]
        - equal: [ "main", << pipeline.parameters.branchName >> ]
    jobs:
      - prod-deploy

#-----

  dev-pr-workflow:
    when:
      and:
        - equal: [ "pr", << pipeline.parameters.eventType >> ]
        - equal: [ "dev", << pipeline.parameters.branchName >> ]
    jobs:
      - developer-predeploy
  
  qa-pr-workflow:
    when:
      and:
        - equal: [ "pr", << pipeline.parameters.eventType >> ]
        - equal: [ "qa", << pipeline.parameters.branchName >> ]
    jobs:
      - qa-predeploy

  uat-pr-workflow:
    when:
      and:
        - equal: [ "pr", << pipeline.parameters.eventType >> ]
        - equal: [ "uat", << pipeline.parameters.branchName >> ]
    jobs:
      - uat-predeploy

  prod-pr-workflow:
    when:
      and:
        - equal: [ "pr", << pipeline.parameters.eventType >> ]
        - equal: [ "main", << pipeline.parameters.branchName >> ]
    jobs:
      - prod-predeploy