version: 2.1

parameters:
  eventType:
    default: "test"
    type: string
    
  branchName:
    default: "test"
    type: string   

  sourceBranchName:
    default: "test"
    type: string


#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
jobs:
  developer-deploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run:
          name: "DEV PUSH"
          command: npm --version

      - run:
          name: "SET EVENT_TYPE"
          command: EVENT_TYPE = << pipeline.parameters.eventType >>

      - run:
          name: "SET EVENT_TYPE"
          command: BRANCH_NAME = << pipeline.parameters.branchName >>

      - run:
          name: "SET EVENT_TYPE"
          command: SOURCE_BRANCH_NAME = << pipeline.parameters.sourceBranchName >>

      #- run: 
      #    name: "SET VARIABLES"
      #    command: |
      #      EVENT_TYPE = << pipeline.parameters.eventType >>
      #      EVENT_TYPE = << pipeline.parameters.branchName >>
      #      EVENT_TYPE = << pipeline.parameters.sourceBranchName >>

      - run:
          name: "Deploy data to Dev Env"
          command: . build/deploy_to_developer_sf_org.sh



workflows:
  version: 2
  dev-push-workflow:
    when:
      and:
        - equal: [ "push", << pipeline.parameters.eventType >> ]
        - equal: [ "dev", << pipeline.parameters.branchName >> ]
    jobs:
      - developer-deploy