version: 2.1

parameters:
  run_test_workflow:
    default: false
    type: boolean

jobs:
  developer-deploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - run:
          name: "NPM vers ion check"
          command: npm --version

workflows:
  version: 2
  test-workflow:
    when: << pipeline.parameters.run_test_workflow >>
    jobs:
      - developer-deploy


#workflows:
#  developer-workflow:
#    jobs:
#      - developer-deploy:
#          filters:
#            branches:
#              only: dev