name: CI


on:
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: dev push
        run: |
            curl --request POST \
            --url https://circleci.com/api/v2/project/gh/ArtBubnov/euro_test_3/pipeline \
            --header 'Circle-Token: 6da8a1e6759256c342785b7315374722adca636a' \
            --header 'content-type: application/json' \
            --data '{"branch":"dev","parameters":{"eventType":"push", "branchName":"dev", "sourceBranchName":"false"}}'