name: CI


on:
  push:
    patch:
      - './'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: git terst
        run: |
          git branch --contains 7cf1acc
          echo $GITHUB_WORKSPACE
          git checkout dev
          git branch --contains 7cf1acc


      - name: my test
        run: git branch

      - name: variable test
        run: |
          echo "SECRET TEST"
          echo ${{ secrets.CIRCLE_CI_API}}
          echo $GITHUB_REF_NAME
          echo "**************"
          echo $GITHUB_HEAD_REF
          echo "----------------"
          echo -e '{"branch":"'$GITHUB_REF_NAME'","parameters":{"eventType":"push", "branchName":"'$GITHUB_REF_NAME'", "sourceBranchName":"false"}}'


      #- name: dev push
      #  run: |
      #      curl --request POST \
      #      --url https://circleci.com/api/v2/project/gh/ArtBubnov/euro_test_3/pipeline \
      #      --header 'Circle-Token: '${{ secrets.CIRCLE_CI_API}} \
      #      --header 'content-type: application/json' \
      #      --data '{"branch":"'$GITHUB_REF_NAME'","parameters":{"eventType":"push", "branchName":"'$GITHUB_REF_NAME'", "sourceBranchName":"false"}}'
