name: CI


on:
  pull_request:
    types: [opened, reopened, edited]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: dev pull request
        run: |
            curl --request POST \
            --url https://circleci.com/api/v2/project/gh/EurostarDigital/salesforce/pipeline \
            --header 'Circle-Token: '${{ secrets.CIRCLE_CI_API}} \
            --header 'content-type: application/json' \
            --data '{"branch":"'${{ github.event.pull_request.base.ref }}'","parameters":{"eventType":"pr", "branchName":"'${{ github.event.pull_request.base.ref }}'", "sourceBranchName":"'${{ github.event.pull_request.head.ref }}'"}}'