name: CI


on:
  pull_request:
    branches:
      - dev

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: variable test
        run: |
          echo "test"
          echo $GITHUB_REF_NAME
          echo $GITHUB_HEAD_REF

      - name: dev pull request
        run: |
            curl --request POST \
            --url https://circleci.com/api/v2/project/gh/ArtBubnov/euro_test_3/pipeline \
            --header 'Circle-Token: 7a87730dbe7ce5fdc8b4c5129bf095ad2d6d954a' \
            --header 'content-type: application/json' \
            --data '{"branch":"dev","parameters":{"eventType":"pr", "branchName":"dev", "sourceBranchName:$GITHUB_HEAD_REF"}}'