name: CI


on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: main push
        run: echo Hello, world!

      - name: test rest api call circleci
        run: curl --request POST \
            --url https://circleci.com/api/v2/project/gh/ArtBubnov/euro_test_3/pipeline \
            --header 'Circle-Token: 7a87730dbe7ce5fdc8b4c5129bf095ad2d6d954a' \
            --header 'content-type: application/json' \
            --data '{"parameters":{"run_dev_push":false, "run_qa_push":false, "run_uat_push":false, "run_prod_push":true, "run_dev_PR":false, "run_qa_PR":false, "run_uat_PR":false, "run_prod_PR":false}}'