name: CI


on:
  push:
    branches:
      - qa

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: qa push
        run: |
            curl --request POST \
            --url https://circleci.com/api/v2/project/gh/ArtBubnov/euro_test_3/pipeline \
            --header 'Circle-Token: 7a87730dbe7ce5fdc8b4c5129bf095ad2d6d954a' \
            --header 'content-type: application/json' \
            --data '{"branch":"qa","parameters":{"run_dev_push":false, "run_qa_push":true, "run_uat_push":false, "run_prod_push":false, "run_dev_PR":false, "run_qa_PR":false, "run_uat_PR":false, "run_prod_PR":false}}'