name: CI


on:
  push:
    branches:
      - uat

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: uat push
        run: echo Hello, world!

      - name: test rest api call circleci
        run: curl google.com